services:
  webclient:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-webclient
    environment:
      BASE_URL: ${BASE_URL}
    ports:
      - "${PORT:-11948}:80"
