name: agent-webclient

services:
  webclient:
    container_name: agent-webclient
    image: agent-webclient:${WEBCLIENT_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      BASE_URL: ${BASE_URL}
      VOICE_BASE_URL: ${VOICE_BASE_URL}
    ports:
      - "${HOST_PORT:-11948}:80"
