FROM nginx:1.27-alpine
RUN apk add --no-cache gettext

COPY dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf.template
COPY nginx-entrypoint.sh /usr/local/bin/nginx-entrypoint.sh
RUN chmod +x /usr/local/bin/nginx-entrypoint.sh

EXPOSE 80

CMD ["/usr/local/bin/nginx-entrypoint.sh"]
