export function createState() {
  return {
    agents: [],
    chats: [],
    agentKey: '',
    selectedAgentLocked: '',
    chatId: '',
    runId: '',
    requestId: '',
    streaming: false,
    abortController: null,
    messagesById: new Map(),
    messageOrder: [],
    events: [],
    debugLines: [],
    plan: null,
    planRuntimeByTaskId: new Map(),
    planCurrentRunningTaskId: '',
    planLastTouchedTaskId: '',
    toolStates: new Map(),
    toolNodeById: new Map(),
    contentNodeById: new Map(),
    pendingTools: new Map(),
    reasoningNodeById: new Map(),
    reasoningCollapseTimers: new Map(),
    actionStates: new Map(),
    executedActionIds: new Set(),
    renderedViewportSignatures: new Set(),
    timelineNodes: new Map(),
    timelineOrder: [],
    timelineNodeByMessageId: new Map(),
    timelineDomCache: new Map(),
    timelineCounter: 0,
    renderQueue: {
      dirtyNodeIds: new Set(),
      scheduled: false,
      stickToBottomRequested: false,
      fullSyncNeeded: true
    },
    activeReasoningKey: '',
    chatFilter: '',
    chatLoadSeq: 0,
    settingsOpen: false,
    activeDebugTab: 'events',
    leftDrawerOpen: false,
    rightDrawerOpen: false,
    layoutMode: 'mobile-drawer',
    planExpanded: false,
    planManualOverride: null,
    planAutoCollapseTimer: null,
    viewportExpanded: false,
    mentionOpen: false,
    mentionSuggestions: [],
    mentionActiveIndex: 0,
    activeFrontendTool: null,
    accessToken: ''
  };
}
